
name: Update Deployment Status and Log to Supabase
# This workflow updates the deployment status and logs it to Supabase

on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  update_supabase:
    runs-on: ubuntu-latest
    
    steps:
      - name: Capture start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log and Update Deployment
        if: always()
        uses: ramaeondev/therama.dev/.github/actions/log-and-update-deployment@master
        with:
          start_time: ${{ env.START_TIME }}
          s3_bucket: ${{ secrets.S3_UPLOAD_BUCKET }}